server:
  port: 8081
  servlet:
    context-path: /api

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/freedom_fm?useSSL=false
    username: <your DB username>
    password: <your DB password>
  jpa:
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.gmail.com
    port: 587
    username: <your-email@gmail.com>
    password: <your password>
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: <your Okta issuer URI>

app:
  path:
    uploadDir: E:\\projects\\FreedomFM\\i-am-singer\\front-end\\public\\songs
  max-songs: 10
  max-code-length: 10

email-service:
  email: freedomfm@gmail.com
  sender: FreedomFM

email-template:
  links:
    contest: http://localhost:3000
    facebook: https://www.facebook.com/RadioFreedom104.7
    instagram: https://www.instagram.com/radio_freedomfm/
  logos:
    logo-freedom-fm: static/images/logo-freedom-fm.png
    logo-facebook: static/images/logo-facebook.png
    logo-instagram: static/images/logo-instagram.png

logging:
  level:
    root: DEBUG